Solution Ex2
deremenko/Js_Pract pull request #2
Opened 2023-12-12 10:49 UTC by deremenko

Two correct solutions. Please indicate which one is more acceptable to you

2023-12-14 08:51 UTC, baklanovairina requested changes

2023-12-14 08:51 UTC, baklanovairina commented on Ex_2.js
> +const cutStr = (str)=>{
еще поработай над неймингом функции и не сокращаем слова в названиях
буквы у нас бесплатные

2023-12-14 08:51 UTC, baklanovairina commented on Ex_2.js
> +   if (str.length>5) {
пробелы ставь

2023-12-14 08:51 UTC, baklanovairina commented on Ex_2.js
> +       return str.slice(0,3)+str.slice(-3)
табы 2 пробела
и точки с запятой расставь

2023-12-14 08:51 UTC, baklanovairina commented on Ex_2.js
> +   }else {
else излишен, т к у тебя выше return есть, код вниз и так не пойдет

2023-12-19 07:19 UTC, baklanovairina requested changes

2023-12-19 07:19 UTC, baklanovairina commented on Ex_2.js
> +const trimmerLine = (str) => {
глагола в названии функции все еще нет

2023-12-19 07:19 UTC, baklanovairina commented on Ex_2.js
> +  } else {
используй тернарный оператор

2023-12-19 08:31 UTC, deremenko commented on Ex_2.js
> +  } else {
Но ведь читаемость падает...

2023-12-21 09:47 UTC, baklanovairina commented on Ex_2.js
> +}
табы
```
const trimLine = (str) => {
  str.length > 5
    ? str.slice(0, 3) + str.slice(-3) 
    : str[0].repeat(str.length);
}
```

и еще ты ничего не возвращаешь из функции, поэтому undefined

2023-12-22 03:04 UTC, merged